config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'public_recipes#index'
  resources :users, only: [:index, :show]
  resources :public_recipes, only: [:index]
  resources :recipe_foods, only: [:new, :create, :destroy]
  resources :foods, only: [:index, :new, :create, :destroy]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
    resources :shopping_lists, only: [:index]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:

    # can :manage, Food, user: user
    # can :read, Recipe, user: user
    # can :manage, Recipe, user: user

    # user ||= User.new

    # can :read, Recipe do |recipe|
    #   recipe.public? || recipe.user == user
    # end

    # can :destroy, Recipe do |recipe|
    #   recipe.user == user
    # end

    # can :read, Food

    # can :destroy, Food do |food|
    #   food.user.id == user.id
    # end

    # can %i[create], :all

    return unless user.present?

    can :read, Recipe, user: user
    can :manage, Recipe, user: user
    can :manage, Food, user: user
    can :manage, RecipeFood, user: user
    return unless user.role == 'admin'

    can :manage, :all

    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: { message: "Name can't be null" }, length: { in: 3..10 }, uniqueness: true
  validates :measurement_unit, presence: { message: "Measurement unit can't be null" }
  validates :price, presence: { message: "Price can't be null" }
  validates :price, numericality: { only_float: true, greater_than: 0, message: 'Price must be greater than 0' }

  belongs_to :user
  has_many :recipe_foods, dependent: :delete_all
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true

  # has_many :foods, dependent: :delete_all
  # has_many :recipes, dependent: :delete_all

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :delete_all
  has_many :recipes, dependent: :delete_all

  validates :name, presence: true

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  #   before_action :authenticate_user!

  def index
    @foods = Food.all.includes([:user])
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    if @food.save
      redirect_to foods_path,
                  notice: 'Food was added successfully.'
    else
      render :new, alert: 'Failed to add food'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path,
                notice: 'Food was successfully destroyed.'
  end

  def food_params
    pp params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true).includes([:recipe_foods]).includes([:user])
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.create(recipe_foods_params)

    if @recipe_food.save
      redirect_to @recipe, notice: 'Recipe was added successfully.'
    else
      render :new, notice: 'Recipe was not added.'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Delete item successfully.'
  end

  private

  def recipe_foods_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all.includes([:user])
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes([:food])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe was added successfully.'
    else
      render :new, alert: 'Failed to add recipe'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe was successfully destroyed.'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :user_id, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = @recipe.recipe_foods.includes([:food])
    @total = get_total(@recipe_foods)
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = @recipe.recipe_foods.includes([:food])
  end

  private

  def get_total(recipe_foods)
    output = 0
    recipe_foods.each do |element|
      output += element.food.price * element.quantity.to_i
    end
    output
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    redirect_to new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/_form.html.erb
<h2>Add Food</h2>
<%= form_with model: @food, url: foods_path, method: :post do |form| %>
  <div class="mb-3">
    <%= form.label :Name, class:'form-label' %><br>
    <%= form.text_field :name, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :'Measurement Unit: ' %><br>
    <%= form.text_field :measurement_unit, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :"Unit Price:" %><br>
    <%= form.text_field :price, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit :'Create Food', class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/foods/index.html.erb
<h3><%= link_to 'Add food', new_food_path %></h3>

<table class="table table-striped table-bordered table-hover">
    <% if @foods.empty? %>
      <p>No food here, please add food</p>
    <% else %>
      <thead class="table-dark">
        <tr>
          <th>Name</th>
          <th>Measurement Unit</th>
          <th>Unit Price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>

        <% @foods.each do |food| %>
          <% if can? :read, food %>
            <tr>
              <td><%= food.name %></td>
              <td><%= food.measurement_unit %></td>
              <td><span>$<%= food.price %></span></td>
              <td>
              
              <%= link_to "Delete Food", food_path(food), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %></td>
                    
            </tr>
          <% end %>
        <% end %>

      </tbody>
    <% end %>
  </table>

app/views/foods/new.html.erb
<h3><%= render partial: 'form' %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>

  <body>
    <%=render "shared/navbar" %>
    <div class="container mt-2">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/public_recipes/index.html.erb
<h4 class="fw-bold">Public Recipes</h4>
<div>
  <ul class="m-0 p-0">
    <% @recipes.each do |recipe| %>
    <li class="card list-style-none mb-3">
      <div class="card-header fs-4">
        <%= link_to recipe.name, recipe_path(recipe.id) %>
      </div>
      <div class="card-body">
        <p class="card-title fw-bold">By: <%= recipe.user.name %></p>
        <p class="card-text fs-6 mb-4">
          <span class="fw-bold">Description:</span><br />
          <%= recipe.description %>
        </p>
        <div class="d-flex justify-content-between">
          <span class="card-text fw-bold"
            >Total food items: <%= recipe.recipe_foods.length %> </span
          ><br />
        <%# <% if can? :destroy, recipe %>
          <%= button_to 'Remove',
            recipe_path(recipe), method: :delete, class: "btn btn-danger
            text-decoration-none" %> 
          <%# <% end %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/recipe_foods/new.html.erb
<section class="w-50 h-50 p-3 mx-auto border">

  <%= form_with model: [@recipe, @recipe.recipe_foods.create] do |form|%>
  
    <div class="">
      <%= form.select :food_id, Food.all.collect {|food| [food.name, food.id]},{
      include_blank: " - Select aliment - "}, required: true, class:"w-100" %>
    </div>

    <br />

    <div class="">
      <%= form.number_field :quantity , class:"w-100b" , required: true, placeholder: :quantity, min: 1%>
    </div>

    <br />


    <div class="d-flex justify-content-xl-between">
      <%= form.submit "Add", class:"btn btn-primary" %>
      <%=link_to 'Back to the recipe', recipe_path(@recipe.id), class:"btn btn-danger"%>
    </div>

  <%end%>

</section>

app/views/recipes/_recipe-form.html.erb
<h2>Add Recipe</h2>
<%= form_with model: @recipe, url: recipes_path, method: :post do |form| %>
  <div class="mb-3">
    <%= form.label :Name, class:'form-label' %><br>
    <%= form.text_field :name, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :'Preparation_Time: ' %><br>
    <%= form.text_field :preparation_time, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :"Cooking_time:" %><br>
    <%= form.text_field :cooking_time, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :"Description:" %><br>
    <%= form.text_field :description, class:'form-control' %>
  </div>

  <div class="custom-control custom-checkbox">
    <%= form.label :"public:" %>
    <%= form.check_box :public %>
  </div>

  <div class="mb-3">
    <br>
    <%= form.submit :'Create Recipe', class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<h3><%= link_to 'Add Recipe', new_recipe_path %></h3>
<table class="table table-striped table-bordered table-hover">

  <% if @recipes.empty? %>
    <p>No recipe here, please add recipe</p>
  <% else %>
  
    <% @recipes.each do |recipe| %>

      <% if can? :read, recipe %>

        <%= link_to recipe_path(recipe.id, recipe) do %>
          <article class='border d-flex'>
            <div class='border col-2 d-flex flex-column justify-content-center align-items-center'>
              <h4><%= recipe.name %></h4>
              <%= link_to "Remove", recipe_path(recipe), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, class: "btn btn-danger" %>
            </div>      

            <div class='border col'>
                  <%= recipe.description %>
            </div> 

          </article>
        <% end %>
        <br />

      <% end %>
    
    <% end %> 

  <% end %>
</table>

app/views/recipes/new.html.erb
<h3><%= render partial: 'recipes/recipe-form' %></h3>

app/views/recipes/show.html.erb
<section class='w-75 p-3 border mx-auto'>

  <div class='d-flex justify-content-center'>
    <h3><%= @recipe.name %></h3>
  </div>

  <div>
    <div class='d-flex justify-content-xl-between'>
    
      <span>Preparation time: <%= @recipe.preparation_time %> </span>
      
      <div class="custom-control custom-checkbox">
        <label class="custom-control-label" for="customCheck1">Public</label>

        <% if @recipe.public? %>
            <input type="checkbox" checked class="custom-control-input" id="customCheck1">
        <% else %>
            <input type="checkbox" class="custom-control-input" id="customCheck1">
        <% end %>
      </div>


    </div>

    <span>Cooking time: <%= @recipe.cooking_time %></span>
  </div>

  <br />

  <div class='d-flex justify-content-xl-between'>

    <button type="button" class="btn btn-primary btn-sm text-decoration-none">
      <%= link_to 'Generate shopping list', recipe_shopping_lists_path(@recipe) %>
    </button>

    <button type="button" class="btn btn-primary btn-sm">
      <%= link_to new_recipe_recipe_food_path(@recipe), :class => "Add ingredients" do %>
       Add Ingredients
      <% end %>
      
    </button>

  </div>

  <hr />

  <table class='table table-striped table-bordered table-hover'>

    <thead class='table-dark'>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>

      <% if @recipe_foods.empty? %>
        <p>No ingredients</p>
      <% end %>

      <tbody>
        <% @recipe_foods.each do |recipe| %>
          <tr>
            <td><%= recipe.food.name %></td>
            <td><%= recipe.quantity %></td>
            <td><%= recipe.food.price %></td>
            <td>
              <%# <% if can? :update, @recipe %> 
              <div class='d-flex justify-content-xl-around'>

                <%= button_to "Delete", recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe.id), method: :delete, class:"btn btn-danger btn-sm"%>
                
              </div>
              <%# <% end %>
          </td>
            </td>
          </tr>
        <% end %>
      </tbody>
    <tr>

    </tr>
  </table>

</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <h2 class= "navbar-brand">
    <%= link_to 'RecipesApp', root_path %>
    </h2>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in?%>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Foods', foods_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to 'Recipes', recipes_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to 'Public recipes', public_recipes_path, class:"nav-link"  %>
          </li>
        </ul>
        <ul class="d-flex navbar-nav mb-2 mb-lg-0">
          <li class="nav-item">
            <h4 class="text-white">Welcome <%= current_user.name %></h4>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"nav-link"%>
          </li>
        </ul>
      </div>
    <% else %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            
          </li> 
        </ul>
        <ul class="d-flex navbar-nav mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Log In", new_user_session_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
            </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/shopping_lists/index.html.erb
<div class="d-flex justify-content-center">
    <h1>Shopping Lists</h1>
</div>

<div class="d-flex justify-content-between">
		<h5>Amount of food items to buy: <%= @recipe_foods.count %> </h4>
		<h5>Total price of food needed: <%= @total %></h5>
</div>

<br />

<table class='table table-striped table-bordered table-hover w-75 mx-auto'>
  <thead class='table-dark'>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_foods.each do |food| %>
      <tr>
        <td><%= food.food.name %></td>
        <td><%= food.quantity %> <%= food.food.measurement_unit %></td>
        <td><span>$<%= food.food.price * food.quantity.to_i%></span></td>
      </tr>
    <% end %>
  </tbody>

</table>

<button class="btn btn-danger" >
  <%= link_to 'Come back', recipe_path(@recipe.id)%>
</button>